# Generated by Django 4.2.4 on 2023-09-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_shop_sizes_news_views_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
